### ISSUE TITLE
Route 53 Split-horizon DNS

### ISSUE THREAD

**Issue by itomaldonado** [tazjin/kubernetes-letsencrypt#61]
When using split-horizon DNS in AWS we have two hosted zones (a private and a public one) with the same domain. 

Right now the service is choosing the first one it finds (which is the private one) and LE verification times out.

Since for LE to verify your cert it needs to do a public DNS lookup, this service should default to the Public hosted-zone if it finds more than one zone with the same domain.

**Comment by itomaldonado** [comment]
I am taking a stab at it if you want to....

**Comment by tazjin** [comment]
Thanks for pointing this out, I'll take a look soon!

**Comment by tazjin** [comment]
Fixed in #64

**Comment by itomaldonado** [comment]
@tazjin Just wanted to put this here for future reference. If you are using split-brain DNS it *is* possible for the application to resolve to the "private" name servers. To force the application to use an external DNS for resolving the name spaces make sure you do add the environment variable "LETSENCRYPT_CONTROLLER_OPTS" as seen below (the example uses google's DNS server).


```
...
    spec:
      serviceAccountName: letsencrypt
      containers:
        - image: tazjin/letsencrypt-controller:1.7
          imagePullPolicy: Always
          name: letsencrypt-controller
          env:
          - name: LETSENCRYPT_CONTROLLER_OPTS
            value: "-Ddns.server=8.8.8.8"
...
```
